In [12]:
import pandas as pd

In [13]:
# load dataset
ds_cleaner = pd.read_excel("Pandas_Practice.xlsx", sheet_name="Sheet1")
ds_cleaner.head()

,OrderID,OrderDate,Customer,Region,Product,Category,Quantity,UnitPrice,Discount,Revenue
0,1001,2024-01-13,David Davis,South,Smartphone,Electronics,4,672.97,0.10,2422.6920
1,1002,2024-08-04,Mary Smith,North,Water Bottle,Accessories,8,22.02,0.00,176.1600
2,1003,2024-11-28,Betty Anderson,South,Desk Chair,Furniture,19,172.01,0.20,2614.5520
3,1004,2024-12-23,Susan Hernandez,East,Headphones,Electronics,7,130.97,0.00,916.7900
4,1005,2024-07-13,Patricia Lopez,East,Smartphone,Electronics,9,689.93,0.15,5277.9645

In [14]:
ds_cleaner.shape

(50, 10)

In [15]:
ds_cleaner.dtypes

OrderID               int64
OrderDate    datetime64[ns]
Customer             object
Region               object
Product              object
Category             object
Quantity              int64
UnitPrice           float64
Discount            float64
Revenue             float64
dtype: object

In [16]:
ds_cleaner.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderID    50 non-null     int64
 1   OrderDate  50 non-null     datetime64[ns]
 2   Customer   50 non-null     object
 3   Region     47 non-null     object
 4   Product    50 non-null     object
 5   Category   50 non-null     object
 6   Quantity   50 non-null     int64
 7   UnitPrice  48 non-null     float64
 8   Discount   50 non-null     float64
 9   Revenue    50 non-null     float64
dtypes: datetime64[ns](1), float64(3), int64(2), object(4)
memory usage: 4.0+ KB

In [17]:
ds_cleaner.describe()

,OrderID,OrderDate,Quantity,UnitPrice,Discount,Revenue
count,50.00000,50,50.000000,48.000000,50.000000,50.000000
mean,1025.50000,2024-06-12 19:40:48,11.380000,241.598333,0.088000,2423.131190
min,1001.00000,2024-01-01 00:00:00,2.000000,5.480000,0.000000,0.000000
25%,1013.25000,2024-03-04 12:00:00,8.000000,21.360000,0.000000,176.497500
50%,1025.50000,2024-05-31 00:00:00,10.500000,112.410000,0.075000,729.232000
75%,1037.75000,2024-09-07 12:00:00,15.750000,447.087500,0.150000,3563.704125
max,1050.00000,2024-12-26 00:00:00,20.000000,969.140000,0.200000,16572.294000
std,14.57738,NaN,5.193756,281.578804,0.079898,3492.448743

In [18]:
ds_cleaner.isna().sum()

OrderID      0
OrderDate    0
Customer     0
Region       3
Product      0
Category     0
Quantity     0
UnitPrice    2
Discount     0
Revenue      0
dtype: int64

In [19]:
ds_cleaner.iloc[8:11]

,OrderID,OrderDate,Customer,Region,Product,Category,Quantity,UnitPrice,Discount,Revenue
8,1009,2024-11-07,Jennifer Lee,South,Smartphone,Electronics,15,634.33,0.15,8087.7075
9,1010,2024-04-22,William Johnson,South,Backpack,Accessories,11,53.91,0.00,593.0100
10,1011,2024-06-10,Michael Moore,West,Water Bottle,Accessories,15,20.43,0.00,306.4500

In [20]:
ds_cleaner.loc[9, ["OrderID", "OrderDate", "Customer", "Region", "Product", "Category", "Quantity", "UnitPrice", "Discount", "Revenue"]]

OrderID                     1010
OrderDate    2024-04-22 00:00:00
Customer         William Johnson
Region                     South
Product                 Backpack
Category             Accessories
Quantity                      11
UnitPrice                  53.91
Discount                     0.0
Revenue                   593.01
Name: 9, dtype: object

In [23]:
specific_customer = ds_cleaner.loc[ds_cleaner["Customer"]=="William Johnson"]
specific_customer

,OrderID,OrderDate,Customer,Region,Product,Category,Quantity,UnitPrice,Discount,Revenue
9,1010,2024-04-22,William Johnson,South,Backpack,Accessories,11,53.91,0.0,593.010
29,1030,2024-02-01,William Johnson,North,Backpack,Accessories,16,55.03,0.2,704.384

In [27]:
price_screen = ds_cleaner["UnitPrice"] > 50
price_screen

0      True
1     False
2      True
3      True
4      True
5      True
6      True
7     False
8      True
9      True
10    False
11     True
12    False
13     True
14     True
15     True
16     True
17     True
18     True
19     True
20     True
21     True
22    False
23     True
24     True
25    False
26     True
27    False
28     True
29     True
30     True
31    False
32     True
33    False
34     True
35     True
36     True
37     True
38     True
39    False
40    False
41     True
42     True
43    False
44    False
45    False
46     True
47     True
48    False
49    False
Name: UnitPrice, dtype: bool

In pandas (and Python in general), square brackets [ ] are used for getting, setting, or indexing data, while parentheses ( ) are used for doing actions (calling functions) or grouping logic.

In [31]:
price_screen = ds_cleaner.loc[ds_cleaner["UnitPrice"] > 500]
price_screen

,OrderID,OrderDate,Customer,Region,Product,Category,Quantity,UnitPrice,Discount,Revenue
0,1001,2024-01-13,David Davis,South,Smartphone,Electronics,4,672.97,0.10,2422.6920
4,1005,2024-07-13,Patricia Lopez,East,Smartphone,Electronics,9,689.93,0.15,5277.9645
8,1009,2024-11-07,Jennifer Lee,South,Smartphone,Electronics,15,634.33,0.15,8087.7075
13,1014,2024-07-16,Maria White,West,Smartphone,Electronics,9,711.24,0.20,5120.9280
14,1015,2024-12-15,Betty Rodriguez,East,Smartphone,Electronics,10,641.52,0.05,6094.4400
20,1021,2024-05-06,Linda Williams,East,Smartphone,Electronics,19,657.01,0.10,11234.8710
21,1022,2024-02-06,Mary Davis,North,Laptop,Electronics,11,822.75,0.00,9050.2500
23,1024,2024-12-03,Susan Lopez,NaN,Smartphone,Electronics,15,697.30,0.00,10459.5000
24,1025,2024-02-01,Maria Hernandez,North,Smartphone,Electronics,7,609.73,0.05,4054.7045
26,1027,2024-01-26,Betty Smith,North,Smartphone,Electronics,6,637.83,0.05,3635.6310
41,1042,2024-07-02,Michael Davis,NaN,Laptop,Electronics,18,969.14,0.05,16572.2940